// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemManagementService.Infrastructure.Persistence;

namespace SystemManagementService.Migrations
{
    [DbContext(typeof(SystemManagementDatabaseContext))]
    [Migration("20221027042627_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SystemManagementService.Domain.Entities.LPN", b =>
                {
                    b.Property<int>("LpnNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("LpnNo");

                    b.ToTable("LPN");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Node");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Pallet", b =>
                {
                    b.Property<int>("PalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LpnId")
                        .HasColumnType("int");

                    b.Property<int?>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("PalletMaxQuantity")
                        .HasColumnType("int");

                    b.Property<string>("PalletName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PalletQuantity")
                        .HasColumnType("int");

                    b.HasKey("PalletId");

                    b.HasIndex("LpnId");

                    b.HasIndex("NodeId");

                    b.ToTable("Pallet");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int?>("PalletId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("PalletId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WarehouseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Node", b =>
                {
                    b.HasOne("SystemManagementService.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Nodes")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Pallet", b =>
                {
                    b.HasOne("SystemManagementService.Domain.Entities.LPN", "Lpn")
                        .WithMany()
                        .HasForeignKey("LpnId");

                    b.HasOne("SystemManagementService.Domain.Entities.Node", "Node")
                        .WithMany("Pallets")
                        .HasForeignKey("NodeId");

                    b.Navigation("Lpn");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Product", b =>
                {
                    b.HasOne("SystemManagementService.Domain.Entities.Pallet", "Pallet")
                        .WithMany("Product")
                        .HasForeignKey("PalletId");

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Node", b =>
                {
                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Pallet", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SystemManagementService.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
